In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)

In [3]:
print(x)

tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  1.2612e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [5]:
x = torch.rand(5,3)

In [6]:
print(x)

tensor([[0.9038, 0.2767, 0.7048],
        [0.4252, 0.6123, 0.4901],
        [0.2785, 0.9918, 0.8658],
        [0.7934, 0.8756, 0.5424],
        [0.9366, 0.7723, 0.6963]])


In [7]:
x = x.new_ones(5,3,dtype=float)

In [19]:
print(x)

tensor([[0.1569, 0.2471, 0.3674],
        [0.9721, 0.6721, 0.2967],
        [0.9551, 0.0400, 0.9248],
        [0.0677, 0.1824, 0.1851],
        [0.7199, 0.6725, 0.2166]], dtype=torch.float64)


In [20]:
s = x.size()
s.count(0)

0

In [36]:
y = torch.rand(5,3)
z = x + y
print(z)
z = torch.add(x,y)
print(z)

result = torch.empty(5,3)

torch.add(x,y, out=result)
print(result)

result = torch.empty(5,3, dtype=torch.double)

y.add_(x)

tensor([[5.7692e-01, 5.7248e-01, 7.2624e-01],
        [2.7779e-01, 4.5752e-01, 4.4758e-01],
        [4.9212e-01, 2.1155e+23, 4.4392e-01],
        [7.1577e-01, 4.3733e-02, 9.8798e-01],
        [2.1259e+20, 2.0566e+20, 6.7050e-01]])
tensor([[5.7692e-01, 5.7248e-01, 7.2624e-01],
        [2.7779e-01, 4.5752e-01, 4.4758e-01],
        [4.9212e-01, 2.1155e+23, 4.4392e-01],
        [7.1577e-01, 4.3733e-02, 9.8798e-01],
        [2.1259e+20, 2.0566e+20, 6.7050e-01]])
tensor([[5.7692e-01, 5.7248e-01, 7.2624e-01],
        [2.7779e-01, 4.5752e-01, 4.4758e-01],
        [4.9212e-01, 2.1155e+23, 4.4392e-01],
        [7.1577e-01, 4.3733e-02, 9.8798e-01],
        [2.1259e+20, 2.0566e+20, 6.7050e-01]])


tensor([[5.7692e-01, 5.7248e-01, 7.2624e-01],
        [2.7779e-01, 4.5752e-01, 4.4758e-01],
        [4.9212e-01, 2.1155e+23, 4.4392e-01],
        [7.1577e-01, 4.3733e-02, 9.8798e-01],
        [2.1259e+20, 2.0566e+20, 6.7050e-01]])

In [37]:
print(y)

tensor([[5.7692e-01, 5.7248e-01, 7.2624e-01],
        [2.7779e-01, 4.5752e-01, 4.4758e-01],
        [4.9212e-01, 2.1155e+23, 4.4392e-01],
        [7.1577e-01, 4.3733e-02, 9.8798e-01],
        [2.1259e+20, 2.0566e+20, 6.7050e-01]])


In [38]:
print(x[:,1])

tensor([0.0000e+00, 0.0000e+00, 2.1155e+23, 6.4836e-10, 2.0566e+20])


In [39]:
print(x)

tensor([[1.4013e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0616e-08, 2.1155e+23, 5.3410e-08],
        [2.1176e-07, 6.4836e-10, 4.2427e-08],
        [2.1259e+20, 2.0566e+20, 1.0781e-08]])


In [41]:
x = torch.randn(4,4)
y = x.view(16)
z = y.view(-1, 8)
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [43]:
import numpy as np
a = np.ones((5,4))
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)


In [45]:
if torch.cuda.is_available():
    
    print('yay')

In [51]:
x = torch.ones(2,2, requires_grad=True)
print(x)

y = x + 2
z = y * y + 6

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [52]:
print(z)

tensor([[15., 15.],
        [15., 15.]], grad_fn=<AddBackward0>)


In [55]:
print(z.grad_fn)
out = z.mean()
print(z, out)

tensor([[15., 15.],
        [15., 15.]], grad_fn=<AddBackward0>) tensor(15., grad_fn=<MeanBackward0>)


In [56]:
out.backward()

In [57]:
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [59]:
x = torch.ones(2,2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

#dout/dx, dout/dy, dout/dz, dout/dout
# z = 3 * (x + 2) ^2
# z = 3 * 9 = 27
# out = 27




In [92]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, 576)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [93]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)


tensor([[-0.0693, -0.1878, -0.0836, -0.0359, -0.1430,  0.0540,  0.0262, -0.0447,
         -0.0450,  0.0226]], grad_fn=<AddmmBackward>)


In [94]:
net.zero_grad()
out.backward(torch.randn(1,10))


In [95]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)

In [96]:
criterion = nn.MSELoss()
loss = criterion(output, target)

In [97]:
print(loss)

tensor(0.5534, grad_fn=<MseLossBackward>)


In [98]:
loss.grad_fn

In [99]:
loss.grad_fn.next_functions[0][0]

In [100]:
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU


In [101]:
net.zero_grad()
loss.backward()

In [102]:
print(net.conv1.bias.grad)


tensor([-0.0030, -0.0010, -0.0019,  0.0061,  0.0057,  0.0105])


In [104]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()